spring:
  datasource:
    name: sxd_database  #数据库名
    url: jdbc:mysql://122.51.97.63:3306/sxd_database?useUnicode=true&characterEncoding=utf8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
## swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
 #开启热部署
  devtools:
    restart:
      enabled: true     #设置开启热部署
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效
  thymeleaf:
    cache: true
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8
    suffix: .html
    encoding: utf-8
#配置mybatis参数
mybatis:
  type-aliases-package: com.example.sxdproject
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true